export const ADD_PACKAGES = 'ADD_PACKAGES';
export const RECEIVE_PACKAGE = 'RECEIVE_PACKAGE';
export const PACKAGES_LOADING = 'PACKAGES_LOADING';
export const PACKAGES_FAILED = 'PACKAGES_FAILED';

export const ADD_DISPATCHES = 'ADD_DISPATCHES';
export const REQUEST_DISPATCH = 'REQUEST_DISPATCH';
export const DISPATCHES_FAILED = 'DISPATCHES_FAILED';

export const ADD_COMMENT = 'ADD_COMMENT';
